-- ============================================================
-- Raw Layer Setup: Internal Stage & Ingestion Table
-- Database: AURA_STREAMS_DB | Schema: RAW_SCHEMA
-- ============================================================
use warehouse AURA_DEV_WH;
use database  AURA_STREAMS_DB;
-- 1. Create the internal stage for uploading CSV files
CREATE OR REPLACE STAGE AURA_STREAMS_DB.RAW_SCHEMA.SPOTIFY_RAW_STAGE
    FILE_FORMAT = (
        TYPE = 'CSV'
        FIELD_OPTIONALLY_ENCLOSED_BY = '"'
        SKIP_HEADER = 1
        EMPTY_FIELD_AS_NULL = TRUE
        NULL_IF = ('NULL', 'null', '')
    );

  
CREATE OR REPLACE TABLE AURA_STREAMS_DB.RAW_SCHEMA.RAW_SPOTIFY_TRACKS_STAGING (
    ROW_NUMBER_RAW VARCHAR,
    TRACK_ID VARCHAR,
    ARTISTS VARCHAR,
    ALBUM_NAME VARCHAR,
    TRACK_NAME VARCHAR,
    POPULARITY VARCHAR,
    DURATION_MS VARCHAR,
    EXPLICIT VARCHAR,
    DANCEABILITY VARCHAR,
    ENERGY VARCHAR,
    KEY_VAL VARCHAR,
    LOUDNESS VARCHAR,
    MODE_VAL VARCHAR,
    SPEECHINESS VARCHAR,
    ACOUSTICNESS VARCHAR,
    INSTRUMENTALNESS VARCHAR,
    LIVENESS VARCHAR,
    VALENCE VARCHAR,
    TEMPO VARCHAR,
    TIME_SIGNATURE VARCHAR,
    TRACK_GENRE VARCHAR
);  
COPY INTO AURA_STREAMS_DB.RAW_SCHEMA.RAW_SPOTIFY_TRACKS_STAGING
FROM @AURA_STREAMS_DB.RAW_SCHEMA.SPOTIFY_RAW_STAGE
FILE_FORMAT = (
    TYPE = 'CSV'
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    EMPTY_FIELD_AS_NULL = TRUE
    NULL_IF = ('NULL', 'null', '')
)
ON_ERROR = 'CONTINUE';

select * from AURA_STREAMS_DB.RAW_SCHEMA.RAW_SPOTIFY_TRACKS_STAGING;