 -- ============================================================
-- Gold Layer Star Schema: Dimensions & Fact Population
-- Database: AURA_STREAMS_DB | Schema: GOLD_SCHEMA
-- ============================================================
use warehouse AURA_DEV_WH;
use database  AURA_STREAMS_DB;
-- 1. Populate Dimension: Artists
CREATE OR REPLACE TABLE AURA_STREAMS_DB.GOLD_SCHEMA.DIM_ARTISTS AS
SELECT 
    ROW_NUMBER() OVER (ORDER BY ARTIST_NAME) AS ARTIST_KEY,
    ARTIST_NAME
FROM (
    SELECT DISTINCT ARTISTS AS ARTIST_NAME 
    FROM AURA_STREAMS_DB.SILVER_SCHEMA.SILVER_SPOTIFY_TRACKS
);

-- 2. Populate Dimension: Genres
CREATE OR REPLACE TABLE AURA_STREAMS_DB.GOLD_SCHEMA.DIM_GENRES AS
SELECT 
    ROW_NUMBER() OVER (ORDER BY TRACK_GENRE) AS GENRE_KEY,
    TRACK_GENRE AS GENRE_NAME
FROM (
    SELECT DISTINCT TRACK_GENRE 
    FROM AURA_STREAMS_DB.SILVER_SCHEMA.SILVER_SPOTIFY_TRACKS
);

-- 3. Populate Dimension: Tracks
CREATE OR REPLACE TABLE AURA_STREAMS_DB.GOLD_SCHEMA.DIM_TRACKS AS
SELECT 
    ROW_NUMBER() OVER (ORDER BY TRACK_ID) AS TRACK_KEY,
    TRACK_ID,
    TRACK_NAME,
    ALBUM_NAME,
    CASE WHEN EXPLICIT = TRUE THEN 'Explicit' ELSE 'Clean' END AS CONTENT_RATING
FROM (
    SELECT DISTINCT TRACK_ID, TRACK_NAME, ALBUM_NAME, EXPLICIT 
    FROM AURA_STREAMS_DB.SILVER_SCHEMA.SILVER_SPOTIFY_TRACKS
);

-- 4. Populate Fact Table: Track Metrics & Audio Profiles with Surrogate Keys
CREATE OR REPLACE TABLE AURA_STREAMS_DB.GOLD_SCHEMA.FACT_TRACK_METRICS AS
SELECT 
    t.TRACK_KEY,
    a.ARTIST_KEY,
    g.GENRE_KEY,
    s.POPULARITY AS POPULARITY_SCORE,
    s.DURATION_SECONDS,
    s.DANCEABILITY,
    s.ENERGY,
    s.ACOUSTICNESS,
    s.VALENCE,
    s.TEMPO,
    s.LOUDNESS,
    s.INSTRUMENTALNESS,
    s.SPEECHINESS,
    s.LIVENESS,
    s.KEY_VAL,
    s.MODE_VAL,
    s.TIME_SIGNATURE
FROM AURA_STREAMS_DB.SILVER_SCHEMA.SILVER_SPOTIFY_TRACKS s
JOIN AURA_STREAMS_DB.GOLD_SCHEMA.DIM_TRACKS t ON s.TRACK_ID = t.TRACK_ID
JOIN AURA_STREAMS_DB.GOLD_SCHEMA.DIM_ARTISTS a ON s.ARTISTS = a.ARTIST_NAME
JOIN AURA_STREAMS_DB.GOLD_SCHEMA.DIM_GENRES g ON s.TRACK_GENRE = g.GENRE_NAME;