-- ============================================================
-- Silver Layer Transformation: Cleaning & Type Casting
-- Database: AURA_STREAMS_DB | Schema: SILVER_SCHEMA
-- ============================================================
use warehouse AURA_DEV_WH;
use database  AURA_STREAMS_DB;
CREATE OR REPLACE TABLE AURA_STREAMS_DB.SILVER_SCHEMA.SILVER_SPOTIFY_TRACKS AS
SELECT 
    -- String Cleaning: Remove surrounding whitespace and handle nulls/empty strings
    NULLIF(TRIM(TRACK_ID), '') AS TRACK_ID,
    COALESCE(NULLIF(TRIM(TRACK_NAME), ''), 'Unknown Track') AS TRACK_NAME,
    COALESCE(NULLIF(TRIM(ARTISTS), ''), 'Unknown Artist') AS ARTISTS,
    COALESCE(NULLIF(TRIM(ALBUM_NAME), ''), 'Unknown Album') AS ALBUM_NAME,
    COALESCE(NULLIF(TRIM(TRACK_GENRE), ''), 'Unassigned') AS TRACK_GENRE,
    
    -- Numeric Casting & Range Validations
    TRY_CAST(POPULARITY AS INT) AS POPULARITY,
    ROUND(TRY_CAST(DURATION_MS AS FLOAT) / 1000.0, 2) AS DURATION_SECONDS,
    
    -- Boolean Handling for Explicit Content
    CASE 
        WHEN UPPER(TRIM(EXPLICIT)) IN ('TRUE', '1', 'YES') THEN TRUE 
        ELSE FALSE 
    END AS EXPLICIT,
    
    -- Audio Features Casting & Clamping (0.0 to 1.0 bounds)
    TRY_CAST(DANCEABILITY AS FLOAT) AS DANCEABILITY,
    TRY_CAST(ENERGY AS FLOAT) AS ENERGY,
    TRY_CAST(KEY_VAL AS INT) AS KEY_VAL,
    TRY_CAST(LOUDNESS AS FLOAT) AS LOUDNESS,
    TRY_CAST(MODE_VAL AS INT) AS MODE_VAL,
    TRY_CAST(SPEECHINESS AS FLOAT) AS SPEECHINESS,
    TRY_CAST(ACOUSTICNESS AS FLOAT) AS ACOUSTICNESS,
    TRY_CAST(INSTRUMENTALNESS AS FLOAT) AS INSTRUMENTALNESS,
    TRY_CAST(LIVENESS AS FLOAT) AS LIVENESS,
    TRY_CAST(VALENCE AS FLOAT) AS VALENCE,
    TRY_CAST(TEMPO AS FLOAT) AS TEMPO,
    TRY_CAST(TIME_SIGNATURE AS INT) AS TIME_SIGNATURE,
    
    -- Silver Audit Metadata
    CURRENT_TIMESTAMP() AS TRANSFORMED_AT

FROM AURA_STREAMS_DB.RAW_SCHEMA.RAW_SPOTIFY_TRACKS_STAGING
WHERE TRIM(TRACK_ID) IS NOT NULL 
  AND TRIM(TRACK_NAME) IS NOT NULL;
  select * from AURA_STREAMS_DB.SILVER_SCHEMA.SILVER_SPOTIFY_TRACKS ;